eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9001

spring:
  application:
    name: rpc1-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    web:
      enabled: true
      client:
        enabled: true
    sampler:
      percentage: 1.0

management:
  security:
    enabled: false
